// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEK11DTlDX9tX0K1H8sym72wFVaqCn8lc',
    appId: '1:186922692877:web:f5c16d9b362ad99eff4044',
    messagingSenderId: '186922692877',
    projectId: 'lifelog-14ee5',
    authDomain: 'lifelog-14ee5.firebaseapp.com',
    storageBucket: 'lifelog-14ee5.firebasestorage.app',
    measurementId: 'G-XYDV78SBGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwN1rRDmKNNHx72HJNbG4mA5w3L73esPU',
    appId: '1:186922692877:android:6660631d262e7c65ff4044',
    messagingSenderId: '186922692877',
    projectId: 'lifelog-14ee5',
    storageBucket: 'lifelog-14ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClnJfeguoxsODj4LcTEjMUWInMQcpP74c',
    appId: '1:186922692877:ios:1160299a51e0b040ff4044',
    messagingSenderId: '186922692877',
    projectId: 'lifelog-14ee5',
    storageBucket: 'lifelog-14ee5.firebasestorage.app',
    iosBundleId: 'com.example.taskLists',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClnJfeguoxsODj4LcTEjMUWInMQcpP74c',
    appId: '1:186922692877:ios:4b8ffc01e0d41e0eff4044',
    messagingSenderId: '186922692877',
    projectId: 'lifelog-14ee5',
    storageBucket: 'lifelog-14ee5.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEK11DTlDX9tX0K1H8sym72wFVaqCn8lc',
    appId: '1:186922692877:web:7a92f8080bf8a78cff4044',
    messagingSenderId: '186922692877',
    projectId: 'lifelog-14ee5',
    authDomain: 'lifelog-14ee5.firebaseapp.com',
    storageBucket: 'lifelog-14ee5.firebasestorage.app',
    measurementId: 'G-MV2WSGLBKV',
  );
}
